### ISSUE TITLE
Deployment image name with colon `:` causes build error (slp4)

### ISSUE THREAD

**Issue by bondowe** [ballerina-platform/module-ballerina-kubernetes#624]
**Description:**
I'm trying to build a a service with a Deployment annotation containing a colon in the image name but I'm getting the following error
```
[2020-09-28 23:54:17,773] SEVERE {b7a.log.crash} - Illegal char <:> at index 21: hello-word-deployment:1-0 
java.nio.file.InvalidPathException: Illegal char <:> at index 21: hello-word-deployment:1-0
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at org.ballerinax.kubernetes.ArtifactManager.setDefaultKubernetesInstructions(ArtifactManager.java:148)
	at org.ballerinax.kubernetes.ArtifactManager.createArtifacts(ArtifactManager.java:72)
	at org.ballerinax.kubernetes.KubernetesPlugin.codeGenerated(KubernetesPlugin.java:275)
	at org.ballerinalang.packerina.task.RunCompilerPluginTask.execute(RunCompilerPluginTask.java:36)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:436)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
```
**Affected Product Version:**
Ballerina SwanLake preview 4 (slp4)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Try building the following with `ballerina build hello_world_k.bal`

```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/kubernetes;

@kubernetes:Service {
    name: "hello-world-service",
    serviceType: "NodePort"
}
@kubernetes:Deployment {
    push: true,
    registry: "index.docker.io/$env{DOCKER_USERNAME}",
    username: "$env{DOCKER_USERNAME}",
    password: "$env{DOCKER_PASSWORD}",    
    name: "hello-word-deployment:1.0",
    namespace: "b7a",
    replicas: 3,
    uberJar: true
}
service hello on new http:Listener(8989) {
    resource function hi(http:Caller caller, http:Request request) {
        final var result = caller->respond("Hello World!\n");
        if result is error {
            log:printError("Error while sending response");
        }
    }
}
```

**Comment by bondowe** [comment]
My bad. I should have use `image` field for image name.
